### ISSUE TITLE
GUI buttons are too much close to OS navigation buttons

### ISSUE THREAD

**Issue by serrq** [you-apps/VibeYou#79] opened 2023-11-16 12:40 UTC
Might you raise the sheet a little more?

OnePlus CPH2399
Android 13
Vibe 2.0

![1000098590](https://github.com/you-apps/VibeYou/assets/113377431/f8657ee0-364d-4fd0-bac3-b72a47c03438)

![1000098593](https://github.com/you-apps/VibeYou/assets/113377431/c7681a9d-ed36-457f-a217-40ee3e7f182f)

**Comment by Bnyro** [comment] 2023-11-16 13:03
Duplicate of #43

**Closed by Bnyro** 2023-11-16 13:03 UTC
Labels: enhancement
